language: csharp
solution: MonoAGS.sln
matrix:
  include: 
    - os: linux
      mono: latest
      env: BUILD_CONFIG=DesktopRelease BUILD_PLATFORM="Any CPU"
      sudo: required
      dist: trusty
      dotnet: 2.0.0
    - os: osx
      mono: latest
      env: BUILD_CONFIG=DesktopRelease BUILD_PLATFORM="Any CPU"
      dotnet: 1.0.1

install:
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner

script:
 - dotnet restore
 - nuget restore MonoAGS.sln
 - msbuild /p:Configuration=$BUILD_CONFIG /p:Platform="$BUILD_PLATFORM" MonoAGS.sln
 - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./Source/Tests/bin/Release/Tests.dll
